---
# File for storing all variable defaults and importing variables from the environment.
# To import, Add the following lines to top of playbooks:
#   vars_files:
#    - /home/ec2-user/master/group_vars/cf_node_var.yml

# Product Versions
jira_version: "8.13.2"
confluence_version: "7.4.6"
bitbucket_version: "7.9.0"

# Default Paths
downloads_path: "/home/ec2-user/downloads"
atl_product_dir: "/home/ec2-user/atlassian"
atl_app_data_dir: "/home/ec2-user/atlassian/application-data"
service_nfs_dir: "/var/atlassian/application-data/shared-home"
node_shared_home: "/home/ec2-user/atlassian/shared-home"
assets_dir: "/home/ec2-user/master/assets"


# Pulled from env
atl_product: "{{ lookup('env', 'ATL_PRODUCT') or 'jira' }}"
atl_product_type: "{{ lookup('env', 'ATL_PRODUCT_TYPE') or 'server' }}"
training_module: "{{ lookup('env', 'TRAINING_MODULE') or '0' }}"
jre_home: "{{ lookup('env', 'JRE_HOME') }}"
java_home: "{{ lookup('env', 'JAVA_HOME') }}"
