---
- name: "Playbook to mount shared NFS storage"
  hosts: localhost
  become: yes
  
  tasks:
    
    - name: "Create shared location for mounting"
      file:
        path: /home/ec2-user/atlassian/shared-home
        state: directory
        owner: ec2-user
        group: root
        mode: 0755
        
    - name: "Run command to mount"
      shell: 'sudo mount -t nfs ServiceNode:/var/atlassian/application-data/shared-home /home/ec2-user/atlassian/shared-home'
      args:
        executable: /bin/bash  