---
- name: "Playbook for downloading and installing Bitbucket Server"
  hosts: localhost
  become: yes
  become_user: ec2-user
  vars_files:
    - /home/ec2-user/master/group_vars/cf_node_var.yml

  tasks:
    
    - name: "Download Bitbucket files"
      get_url:
        url: "{{ item }}"
        dest: '{{ downloads_path }}'
        mode: 0755
      loop:
        - https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-{{ bitbucket_version }}-x64.bin