---
- name: "Playbook for downloading and installing Confluence"
  hosts: localhost
  become: yes
  become_user: ec2-user
  vars_files:
    - /home/ec2-user/master/group_vars/cf_node_var.yml

  tasks:

    - name: "Download Confluence files"
      get_url:
        url: "{{ item }}"
        dest: '{{ downloads_path }}'
        mode: 0755
      loop:
        - https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-{{ confluence_version }}-x64.bin