---
- name: "Playbook to install HAproxy"
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:

    - name: "Install HAproxy"
      yum:
        name: "haproxy"
        state: present

    - name: "Create and configure 'haproxy.cfg'"
      copy:
        force: yes
        src: '{{ assets_dir }}/common/haproxy.cfg'
        dest: '/etc/haproxy/haproxy.cfg'

    - name: "Start service haproxy, if not started"
      service:
        name: haproxy
        state: restarted
