---
- name: "Playbook for installing Jira Data Center"
  hosts: localhost
  become: yes
  become_user: ec2-user
  vars_files:
    - /home/ec2-user/master/group_vars/cf_node_var.yml
    
  tasks:
    
    - name: "Download Jira Software files"
      get_url:
        url: "{{ item }}"
        dest: /home/ec2-user/downloads/
        mode: 0755
      loop:
        - https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.13.1-x64.bin

    - name: "Install fontconfig"
      become: yes
      yum:
        name: fontconfig
        state: present

    - name: Creating Jira app data directory
      file:
        path: '{{ atl_app_data_dir }}/jira'
        state: directory

    - name: "Jira configure dbconfig.xml"
      copy:
        force: no
        src: /home/ec2-user/master/assets/dbconfig.xml
        dest: /home/ec2-user/atlassian/application-data/jira/dbconfig.xml

    - name: "Changing the address to the ServiceNode database"
      replace:
        path: /home/ec2-user/atlassian/application-data/jira/dbconfig.xml
        regexp: "localhost:5432"
        replace: "ServiceNode:5432"

    - name: "Jira installation"
      command: '/home/ec2-user/downloads/atlassian-jira-software-{{ jira_version }}-x64.bin -q -varfile /home/ec2-user/master/assets/jira_response.varfile'
      args:
        creates: /home/ec2-user/atlassian/jira/bin/start-jira.sh

    - name: "Jira cluster setup"
      copy:
        src: /home/ec2-user/master/assets/jira_cluster.properties
        dest: /home/ec2-user/atlassian/application-data/jira/cluster.properties

    - name: "Changing node ID {{ ansible_hostname }}"
      replace:
        path: /home/ec2-user/atlassian/application-data/jira/cluster.properties
        regexp: "CLUSTERID"
        replace: "{{ ansible_hostname }}" 

    - name:  "Starting Jira"
      command: /home/ec2-user/atlassian/jira/bin/start-jira.sh
