---
- name: "Playbook for downloading and installing Jira"
  hosts: localhost
  become: yes
  become_user: ec2-user
  vars_files:
    - /home/ec2-user/master/group_vars/cf_node_var.yml
  
  tasks:

    - name: "Download Jira Software files"
      get_url:
        url: "{{ item }}"
        dest: '{{ downloads_path }}'
        mode: 0755
      register: result
      retries: 5
      delay: 10
      until: result is success
      loop:
        - https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-{{ jira_version }}-x64.bin

    - name: "Install fontconfig"
      become: yes
      yum:
        name: fontconfig
        state: present

    - name: Creating Jira application-data directory
      file:
        path: '{{ atl_app_data_dir }}/jira'
        state: directory

    - name: "Jira installation"
      command: '{{ downloads_path }}/atlassian-jira-software-{{ jira_version }}-x64.bin -q -varfile {{ assets_dir }}/jira/jira_response.varfile'
      args:
        creates: '{{ atl_product_dir }}/jira/bin/start-jira.sh'