---
- name: "Playbook to mount shared NFS storage"
  hosts: localhost
  become: yes

  tasks:

    - name: "Create shared location for mounting"
      file:
        path: /home/ec2-user/atlassian/shared-home
        state: directory
        owner: ec2-user
        group: root
        mode: 0755

    - name: Mount a NFS volume
      ansible.posix.mount:
        src: ServiceNode:/var/atlassian/application-data/shared-home
        path: /home/ec2-user/atlassian/shared-home
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs