---
- name: "Playbook to mount shared NFS storage"
  hosts: localhost
  become: yes
  vars_files:
    - /home/ec2-user/master/group_vars/cf_node_var.yml

  tasks:

    - name: "Create shared location for mounting"
      file:
        path: /home/ec2-user/atlassian/shared-home
        state: directory
        owner: ec2-user
        group: root
        mode: 0755

    - name: "Mount a NFS volume as shared home"
      ansible.posix.mount:
        src: 'ServiceNode:{{ service_nfs_dir }}'
        path: ' {{ node_shared_home }}'
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs