---
- name: "Playbook to setup PostgreSQL with 'atlassian' role"
  hosts: localhost
  become: yes
  
  tasks:

    - name: "Install PostgreSQL9.6"
      shell: amazon-linux-extras install postgresql9.6 vim epel -y
      args:
        creates: /usr/bin/psql
    
    - name: "Install PostgreSQL server packages"
      yum:
        name:
          - postgresql-server
          - postgresql-devel
        state: present
      register: result
      retries: 5
      delay: 5
      until: result is success
    
    - name: "Initial PostgreSQL setup"
      shell: |
        /usr/bin/postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf
    
    - name: "Enable and Start service"
      systemd:
        name: postgresql
        enabled: yes
        state: started
        daemon-reload: yes
    
    - name: "Create the 'atlassian' role"
      become: yes
      become_user: postgres
      shell: |
        psql -c "create role atlassian password 'atlassian' createdb inherit login"
        psql -c "create database jira with owner atlassian encoding 'UTF8'"
        psql -c "create database confluence with owner atlassian encoding 'UTF8'"
        psql -c "grant all privileges on database jira to atlassian"
        psql -c "grant all privileges on database confluence to atlassian"
    
    - name: "Configure 'postgresql.conf' to allow listening on localhost, DC requires '*' instead"
      become: yes
      become_user: postgres
      replace:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: "#listen_addresses = 'localhost'"
        replace: "listen_addresses = '*'"
    
    - name: "Configure 'pg_hba.conf' local IPv4 to trust all"
      become: yes
      become_user: postgres
      replace:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: 'host    all             all             127.0.0.1/32            ident'
        replace: 'host    all             all             127.0.0.1/32            trust'

    - name: "Ensure PostgreSQL pg_hba.conf is configured to allow access from internal network addresses"
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: 'host    all             all             10.0.0.0/8            trust'
        line: 'host    all             all             10.0.0.0/8            trust'
        
    - name: "Restart PostgreSQL"
      systemd:
        name: postgresql
        state: restarted
        daemon_reload: yes
